#!/usr/bin/env node
// Builds the app icon from the logo and regenerates the icons of both apps.
//
//   pnpm icons
//
//   design/logo.svg      the mark, white line art
//   design/app-icon.svg  the mark on a dark disc, so it shows on a light taskbar as well as a dark one
//   design/app-icon.png  the same at 1024 px
//   apps/*/src-tauri/icons  every icon file the app already has, rendered by `tauri icon`

import { copyFileSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const design = path.join(root, 'design');
const apps = ['studio', 'installer'];
const tauri = createRequire(path.join(root, 'apps/studio/package.json')).resolve('@tauri-apps/cli/tauri.js');

const logo = readFileSync(path.join(design, 'logo.svg'), 'utf8');
const viewBox = logo.match(/<svg[^>]*\sviewBox="([^"]+)"/)?.[1];
if (!viewBox) throw new Error('design/logo.svg has no viewBox');
const mark = logo
  .slice(logo.indexOf('>', logo.indexOf('<svg')) + 1, logo.lastIndexOf('</svg>'))
  .replace(/<!--[\s\S]*?-->/g, '')
  .trim()
  .replace(/\n\s*\n/g, '\n');

// 1024 canvas, a disc of radius 480, and the mark 862 px across inside it: the dark rim left
// around the ring keeps its edge visible on light backgrounds.
const size = 1024;
const markSize = 862;
const at = (size - markSize) / 2;
const icon = `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <!-- Generated by scripts/icons.mjs from logo.svg: edit that, then run \`pnpm icons\`. -->
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#2b2b2b"/>
      <stop offset="1" stop-color="#151515"/>
    </linearGradient>
  </defs>
  <circle cx="${size / 2}" cy="${size / 2}" r="480" fill="url(#bg)"/>
  <svg x="${at}" y="${at}" width="${markSize}" height="${markSize}" viewBox="${viewBox}">
    ${mark.replace(/\n/g, '\n  ')}
  </svg>
</svg>
`;
const iconSvg = path.join(design, 'app-icon.svg');
writeFileSync(iconSvg, icon);

const scratch = mkdtempSync(path.join(tmpdir(), 'demido-icons-'));
try {
  const render = (out, ...extra) => {
    execFileSync(process.execPath, [tauri, 'icon', iconSvg, '--output', out, ...extra], {
      cwd: root,
      stdio: 'inherit',
    });
  };

  render(path.join(scratch, 'set'));
  for (const app of apps) {
    const dir = path.join(root, 'apps', app, 'src-tauri', 'icons');
    for (const file of readdirSync(dir)) copyFileSync(path.join(scratch, 'set', file), path.join(dir, file));
  }

  render(path.join(scratch, 'png'), '--png', String(size));
  copyFileSync(path.join(scratch, 'png', `${size}x${size}.png`), path.join(design, 'app-icon.png'));
} finally {
  rmSync(scratch, { recursive: true, force: true });
}
console.log(`Icons written from design/logo.svg for ${apps.join(' and ')}.`);
